services:

  web:
    build: .
    restart: on-failure
    command: gunicorn main:app --bind 0.0.0.0:5000 --access-logfile - --workers 3
    ports:
      - "5000:5000"
    env_file:
      - .env

    volumes:
      - static_volume:/gracias/web/app/static/
      - /home/owiekris/gracia-residences/deployments/nginx:/etc/nginx/conf.d/:ro
      - /home/owiekris/gracia-residences/certbot/www:/var/www/certbot/:ro
      - /home/owiekris/gracia-residences/certbot/conf/:/etc/nginx/ssl/:ro

  nginx:
    build: ./deployments/nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/gracias/web/app/static/
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/owiekris/gracia-residences/certbot/www/:/var/www/certbot/:rw
      - /home/owiekris/gracia-residences/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume:
