services:

  web:
    build: .
    restart: on-failure
    command: gunicorn main:app --bind 0.0.0.0:5000 --access-logfile - --workers 3
    ports:
      - "5000:5000"

    volumes:
      - static_volume:/gracias/app/static/

  nginx:
    build: ./deployments/nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/gracias/app/static/
    depends_on:
      - web

volumes:
  static_volume:
